# Generated by Django 4.1.2 on 2022-12-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_imgfile_announceimg_imgfiles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announceimg',
            old_name='imgFiles',
            new_name='imgFile',
        ),
    ]
