# Generated by Django 4.1.2 on 2022-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_imgfiles_announceimg_imgfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announceimg',
            name='announceCode',
            field=models.CharField(max_length=10),
        ),
    ]
