# Generated by Django 4.0.3 on 2022-12-31 21:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_announceimg_announcecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announceCode', models.CharField(default=api.models.generate_unique_code, max_length=10, unique=True)),
                ('category', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
                ('surface', models.IntegerField()),
                ('willaya', models.CharField(max_length=40)),
                ('commune', models.CharField(max_length=40)),
                ('adress', models.CharField(max_length=256)),
                ('userContacts', models.CharField(max_length=1000)),
                ('userId', models.CharField(max_length=60, unique=True)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
