# Generated by Django 4.0.3 on 2023-02-04 19:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_announce_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagecode', models.CharField(default=api.models.generate_unique_code, max_length=10, unique=True)),
                ('senderEmail', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=1000)),
                ('announceCode', models.CharField(max_length=10)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
