# Generated by Django 4.0.3 on 2023-02-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_formulaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaire',
            name='receiverEmail',
            field=models.CharField(default='receiver', max_length=60),
        ),
    ]
